### ISSUE TITLE
Publish License Info

### ISSUE THREAD

**Issue by commonsguy** [kcrimi/ToolTipDialog#3]
This library seems nice and might fit the need for a project that I am working on. However, I cannot find definitive information about the software license under which it is published:

- The Kotlin files do not have any sort of license header block
- I do not see a `LICENSE` file
- No licensing information is in the project `README`
- [The Android Arsenal listing](https://android-arsenal.com/details/1/8116) says it is GPLv3
- The `bintray.gradle` file says that it is Apache License 2.0

Ideally, it would be clearer what license you are publishing this library under, so we can make sure that we conform to your license requirements.

Thanks for considering this!

**Comment by kcrimi** [comment]
Thanks for the feedback. You're right this is very unclear. 

All places should list Apache v2.0. I will update that ASAP.

**Comment by kcrimi** [comment]
Thanks again for raising this issue. These should all be updated and consistent now 👍
