### ISSUE TITLE
Add customization of background and text color

### ISSUE THREAD

**Issue by Pfuster12** [kcrimi/ToolTipDialog#5]
I think two public methods to set the background and text colors would be essential.

Something like this to add to the chain of methods:

`setTextColor()`

`setBackgroundColor()`

**Comment by kcrimi** [comment]
That's a great request. My next addition will be to allow passing in a theme to the dialog to allow some rich styling options.

In the meantime, you should be able to change the dialog text by setting the `android:colorForeground` in your app's theme
https://github.com/kcrimi/ToolTipDialog/blob/master/tooltipdialog/src/main/res/values/styles.xml#L6

Unfortunately, there's no workaround for the dialog background yet.

**Comment by kcrimi** [comment]
@Pfuster12 1.1.0 has exposed some styling capabilities that you should give you free rein on the text and background styling. 👍
